### ISSUE TITLE
Table Not found while checking for MemCached tables

### ISSUE THREAD

**Issue by faizalrf** [faisalee/ExodusAssess#2]
Failed to Execute: SELECT Concat("`", db_schema, "`.`", db_table, "`") AS resultSet FROM innodb_memcache.containers
java.sql.SQLSyntaxErrorException: (conn=274003) Table 'innodb_memcache.containers' doesn't exist

Stack trace for the exception:

```
java.sql.SQLSyntaxErrorException: (conn=274003) Table 'innodb_memcache.containers' doesn't exist
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:242)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:171)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:238)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:327)
        at org.mariadb.jdbc.MariaDbStatement.executeQuery(MariaDbStatement.java:501)
        at mariadb.migration.mysql.MySQLMain.CheckBySQL(MySQLMain.java:415)
        at mariadb.migration.mysql.MySQLMain.StartExodusAssess(MySQLMain.java:129)
        at mariadb.migration.mysql.MySQLMain.<init>(MySQLMain.java:43)
        at mariadb.migration.ExodusAssess.main(ExodusAssess.java:19)
Caused by: java.sql.SQLException: Table 'innodb_memcache.containers' doesn't exist
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1594)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1453)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1415)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:227)
        at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:321)
        ... 5 more
```

**Comment by faizalrf** [comment]
Solution: Implement better exception handling for this case or check for the table's existence before executing the query.

**Comment by faizalrf** [comment]
Fixed
